# Generated by Django 5.1.15 on 2026-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الشهادة"
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رمز التحقق"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="ملف الشهادة PDF",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإصدار"
                    ),
                ),
            ],
            options={
                "verbose_name": "شهادة التخرج",
                "verbose_name_plural": "شهادات التخرج",
            },
        ),
    ]
