# Generated by Django 5.1.15 on 2026-07-17 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificates", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"role": "trainee"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المتدرب",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certificate",
            unique_together={("trainee", "course")},
        ),
    ]
