# Generated by Django 5.1.15 on 2026-07-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الدورة"),
                ),
                ("description", models.TextField(verbose_name="وصف الدورة")),
                (
                    "hours",
                    models.PositiveIntegerField(
                        default=60, verbose_name="ساعات التدريب"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "الدورة التدريبية",
                "verbose_name_plural": "الدورات التدريبية",
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المحاضرة"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="محتوى المحاضرة"
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                ("start_time", models.TimeField(verbose_name="وقت البدء")),
                ("end_time", models.TimeField(verbose_name="وقت الانتهاء")),
                (
                    "video_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط تسجيل المحاضرة"
                    ),
                ),
                (
                    "files",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="lectures/",
                        verbose_name="ملفات المحاضرة",
                    ),
                ),
            ],
            options={
                "verbose_name": "المحاضرة",
                "verbose_name_plural": "المحاضرات",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المجموعة")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رمز المجموعة"
                    ),
                ),
                (
                    "classroom",
                    models.CharField(max_length=100, verbose_name="القاعة الدراسية"),
                ),
                ("days", models.CharField(max_length=200, verbose_name="أيام التدريب")),
                ("start_time", models.TimeField(verbose_name="وقت البدء")),
                ("end_time", models.TimeField(verbose_name="وقت الانتهاء")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشطة"),
                            ("completed", "مكتملة"),
                            ("paused", "متوقفة مؤقتاً"),
                        ],
                        default="active",
                        max_length=15,
                        verbose_name="حالة المجموعة",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="courses.course",
                        verbose_name="الدورة",
                    ),
                ),
            ],
            options={
                "verbose_name": "المجموعة التدريبية",
                "verbose_name_plural": "المجموعات التدريبية",
            },
        ),
    ]
