# Generated by Django 5.1.15 on 2026-07-17 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "lecturer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instructor_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المدرب/المحاضر",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervisor_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المشرف",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lectures",
                to="courses.group",
                verbose_name="المجموعة",
            ),
        ),
    ]
