# Generated by Django 5.1.15 on 2026-07-27 18:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التقرير"
                    ),
                ),
                (
                    "topics_covered",
                    models.TextField(
                        verbose_name="المواضيع المشروحة والمهارات المغطاة"
                    ),
                ),
                (
                    "attendance_summary",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ملخص الحضور والالتزام",
                    ),
                ),
                (
                    "outstanding_students",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="الطلاب المتميزون خلال اليوم",
                    ),
                ),
                (
                    "struggling_students",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="الطلاب الذين يحتاجون متابعة أو دعم",
                    ),
                ),
                (
                    "challenges_and_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="التحديات والملاحظات العامة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("reviewed", "تم الاطلاع عليها"),
                            ("action_taken", "تم اتخاذ إجراء"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة التقرير",
                    ),
                ),
                (
                    "admin_feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="رد الملاحظات الإدارية"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="courses.group",
                        verbose_name="الشعبة / المجموعة",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المدرب/المحاضر",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="courses.lecture",
                        verbose_name="المحاضرة المرتبطة",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المراجع الإداري",
                    ),
                ),
            ],
            options={
                "verbose_name": "التقرير اليومي للمدرب",
                "verbose_name_plural": "تقارير المدربين اليومية",
                "ordering": ["-created_at"],
            },
        ),
    ]
