# Generated by Django 5.1.4 on 2026-09-04 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_dailyreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lecture",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "المحاضرة والمادة العلمية",
                "verbose_name_plural": "المحاضرات والمواد العلمية",
            },
        ),
        migrations.AddField(
            model_name="lecture",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاريخ الإضافة"
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_lectures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الرفع بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="وقت الانتهاء"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="files",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lectures/",
                verbose_name="ملفات المحاضرة (PDF / مذكرات)",
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="وقت البدء"),
        ),
    ]
