# Generated by Django 5.1.4 on 2026-09-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_lecture_options_lecture_created_at_and_more"),
        ("locations", "0001_initial_governorate_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="locations.branch",
                verbose_name="الفرع / مركز التدريب",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="locations.governorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="code",
            field=models.CharField(max_length=50, verbose_name="رمز المجموعة"),
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("governorate", "code")},
        ),
    ]
