# Generated by Django 5.1.15 on 2026-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityPointsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="النقاط الممنوحة")),
                ("reason", models.CharField(max_length=200, verbose_name="السبب")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="التاريخ والوقت"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل نقاط الفعالية",
                "verbose_name_plural": "سجلات نقاط الفعاليات",
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الشارة")),
                ("description", models.TextField(verbose_name="وصف الشارة")),
                (
                    "icon_name",
                    models.CharField(
                        default="award", max_length=50, verbose_name="أيقونة الشارة"
                    ),
                ),
                (
                    "points_required",
                    models.PositiveIntegerField(
                        default=100, verbose_name="النقاط المطلوبة لفتحها"
                    ),
                ),
            ],
            options={
                "verbose_name": "شارة تفوق",
                "verbose_name_plural": "شارات التفوق",
            },
        ),
        migrations.CreateModel(
            name="TraineeBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الحصول عليها"
                    ),
                ),
            ],
            options={
                "verbose_name": "شارة متدرب",
                "verbose_name_plural": "شارات المتدربين",
            },
        ),
    ]
