# Generated by Django 5.1.15 on 2026-07-17 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gamification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitypointslog",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"role": "trainee"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المتدرب",
            ),
        ),
        migrations.AddField(
            model_name="traineebadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holders",
                to="gamification.badge",
                verbose_name="الشارة",
            ),
        ),
        migrations.AddField(
            model_name="traineebadge",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"role": "trainee"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earned_badges",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المتدرب",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="traineebadge",
            unique_together={("trainee", "badge")},
        ),
    ]
