# Generated by Django 5.1.15 on 2026-07-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="1000 مبرمج",
                        max_length=100,
                        verbose_name="اسم الموقع/المبادرة",
                    ),
                ),
                (
                    "sub_title",
                    models.CharField(
                        default="العتبة الحسينية المقدسة",
                        max_length=150,
                        verbose_name="العنوان الفرعي",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        verbose_name="شعار المبادرة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
                "verbose_name_plural": "إعدادات الموقع",
            },
        ),
    ]
