# Generated by Django 5.1.4 on 2026-07-30 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InitiativeMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="العنوان")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="الوصف والتفاصيل"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "صورة"),
                            ("video", "فيديو"),
                            ("announcement", "إعلان / خبر"),
                        ],
                        default="image",
                        max_length=20,
                        verbose_name="نوع المحتوى",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="initiative_media/images/",
                        verbose_name="الصورة المرفقة",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="initiative_media/videos/",
                        verbose_name="ملف الفيديو",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="رابط فيديو (YouTube / Drive / Vimeo)",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="initiative_media/docs/",
                        verbose_name="ملف مرفق إضافي",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="ظاهر للجميع (العامة والطلاب)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ النشر"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الناشر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ميديا وإعلام المبادرة",
                "verbose_name_plural": "مركز ميديا وإعلام المبادرة",
                "ordering": ["-created_at"],
            },
        ),
    ]
