# Generated by Django 5.1.4 on 2026-09-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial_governorate_branch"),
        ("portal", "0002_initiativemedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiativemedia",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                help_text="اتركه فارغاً لجعل هذا المحتوى وطنياً يظهر لجميع المحافظات",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="locations.governorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="governorate",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_config",
                to="locations.governorate",
                verbose_name="المحافظة (اتركه فارغاً للإعداد الوطني الافتراضي)",
            ),
        ),
    ]
