# Generated by Django 5.1.4 on 2026-09-30 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial_governorate_branch"),
        ("portal", "0004_learninginstruction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="الاسم الكامل")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="رقم الهاتف / واتساب",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "استفسار عام عن المبادرة"),
                            ("registration", "الاشتراك والتسجيل والقبول"),
                            ("technical", "مشكلة تقنية أو خلل في المنصة"),
                            ("courses", "استفسار عن الدورات والمناهج"),
                            ("certificates", "الشهادات والنتائج"),
                            ("suggestion", "اقتراح أو فكرة تطويرية"),
                            ("other", "أخرى"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="نوع الاستفسار",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("normal", "عادية"),
                            ("urgent", "عاجلة"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=250, verbose_name="عنوان الرسالة / الموضوع"
                    ),
                ),
                (
                    "message",
                    models.TextField(verbose_name="نص الرسالة / تفاصيل الاستفسار"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="support_attachments/",
                        verbose_name="مرفق اختياري (صورة/مستند)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديدة / قيد الانتظار"),
                            ("in_progress", "قيد المراجعة والمتابعة"),
                            ("resolved", "تم الحل والرد"),
                            ("closed", "مغلقة"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="حالة الرسالة",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات الإدارة الداخلية"
                    ),
                ),
                (
                    "admin_reply",
                    models.TextField(
                        blank=True, null=True, verbose_name="رد الإدارة المرسل"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, verbose_name="تمت قراءتها من الإدارة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "governorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to="locations.governorate",
                        verbose_name="المحافظة",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_support_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المسؤول المتابع",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسجل (إن وجد)",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة تواصل واستفسار",
                "verbose_name_plural": "رسائل التواصل والاستفسارات",
                "ordering": ["-created_at"],
            },
        ),
    ]
