# Generated by Django 5.1.4 on 2026-09-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Governorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم المحافظة"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="مثال: BAS للبصرة، BGH لبغداد، NJF للنجف",
                        max_length=5,
                        unique=True,
                        verbose_name="كود المحافظة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشطة"),
                            ("inactive", "غير نشطة"),
                            ("coming_soon", "قريباً"),
                        ],
                        default="coming_soon",
                        max_length=15,
                        verbose_name="حالة المحافظة",
                    ),
                ),
                (
                    "launch_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الإطلاق"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="governorates/logos/",
                        verbose_name="شعار المحافظة",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="governorates/covers/",
                        verbose_name="صورة الغلاف",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="وصف النشاط في المحافظة"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني للتواصل",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رقم التواصل"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتيب العرض"
                    ),
                ),
            ],
            options={
                "verbose_name": "المحافظة",
                "verbose_name_plural": "المحافظات",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="اسم الفرع / المركز"),
                ),
                ("code", models.CharField(max_length=10, verbose_name="كود الفرع")),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="العنوان التفصيلي"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="خط العرض"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="خط الطول"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "نشط"), ("inactive", "غير نشط")],
                        default="active",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="المسؤول عن الفرع",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="هاتف الفرع"
                    ),
                ),
                (
                    "governorate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="locations.governorate",
                        verbose_name="المحافظة",
                    ),
                ),
            ],
            options={
                "verbose_name": "الفرع / مركز التدريب",
                "verbose_name_plural": "الفروع ومراكز التدريب",
                "ordering": ["governorate", "name"],
                "unique_together": {("governorate", "code")},
            },
        ),
    ]
