# Generated by Django 5.1.15 on 2026-07-17 10:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "مسؤول النظام (Super Admin)"),
                            ("director", "مدير المبادرة"),
                            ("training_officer", "مسؤول التدريب"),
                            ("supervisor", "المشرف"),
                            ("lecturer", "المحاضر"),
                            ("trainee", "المتدرب"),
                            ("visitor", "الزائر"),
                        ],
                        default="visitor",
                        max_length=20,
                        verbose_name="الدور الوظيفي",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="الرقم الوطني",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "المستخدم",
                "verbose_name_plural": "المستخدمون",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LecturerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(max_length=100, verbose_name="الاختصاص"),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, null=True, verbose_name="السيرة الذاتية"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف المحاضر",
                "verbose_name_plural": "ملفات المحاضرين",
            },
        ),
        migrations.CreateModel(
            name="SupervisorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="القسم المسؤول عنه",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف المشرف",
                "verbose_name_plural": "ملفات المشرفين",
            },
        ),
        migrations.CreateModel(
            name="TraineeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "governorate",
                    models.CharField(max_length=50, verbose_name="المحافظة"),
                ),
                ("district", models.CharField(max_length=50, verbose_name="القضاء")),
                (
                    "university",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="الجامعة"
                    ),
                ),
                (
                    "college",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="الكلية"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="القسم"
                    ),
                ),
                (
                    "academic_stage",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="المرحلة الدراسية",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="الاختصاص"
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ التسجيل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("suspended", "موقف"),
                            ("graduated", "خريج"),
                        ],
                        default="active",
                        max_length=15,
                        verbose_name="حالة الحساب",
                    ),
                ),
                ("points", models.IntegerField(default=0, verbose_name="نقاط الطالب")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainees",
                        to="courses.group",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف المتدرب",
                "verbose_name_plural": "ملفات المتدربين",
            },
        ),
    ]
