# Generated by Django 5.1.15 on 2026-07-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("male", "ذكر"), ("female", "أنثى")],
                default="male",
                max_length=10,
                verbose_name="الجنس",
            ),
        ),
    ]
