# Generated by Django 5.1.15 on 2026-07-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="traineeprofile",
            name="custom_training_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="الرقم التدريبي الخاص",
            ),
        ),
    ]
