# Generated by Django 5.1.15 on 2026-07-26 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_traineeprofile_custom_training_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraineeNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(verbose_name="نص الملاحظة والتوجيه")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مضيف الملاحظة",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_notes",
                        to="users.traineeprofile",
                        verbose_name="المتدرب",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملاحظة وتوجيه الكادر",
                "verbose_name_plural": "ملاحظات وتوجيهات الكادر",
                "ordering": ["-created_at"],
            },
        ),
    ]
