# Generated by Django 5.1.4 on 2026-08-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_traineenote"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="معرف شات التليغرام"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram_link_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="رمز ربط التليغرام"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram_notifications_enabled",
            field=models.BooleanField(
                default=True, verbose_name="تفعيل إشعارات التليغرام"
            ),
        ),
        migrations.AlterField(
            model_name="traineeprofile",
            name="academic_stage",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="المرحلة الدراسية (ابتدائي/متوسط/إعدادي)",
            ),
        ),
        migrations.AlterField(
            model_name="traineeprofile",
            name="college",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الصف الدراسي"
            ),
        ),
        migrations.AlterField(
            model_name="traineeprofile",
            name="department",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="الفرع / الشعبة بالمدرسة",
            ),
        ),
        migrations.AlterField(
            model_name="traineeprofile",
            name="specialty",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="المسار والاهتمام البرمجي",
            ),
        ),
        migrations.AlterField(
            model_name="traineeprofile",
            name="university",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="المدرسة"
            ),
        ),
    ]
