# Generated by Django 5.1.4 on 2026-08-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_telegram_chat_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="temp_password",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="كلمة المرور المؤقتة/المولدة",
            ),
        ),
    ]
