# Generated by Django 5.1.4 on 2026-09-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial_governorate_branch"),
        ("users", "0006_customuser_temp_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                help_text="اتركه فارغاً للمسؤول الوطني (Super Admin) فقط",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="locations.governorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="lecturerprofile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lecturers",
                to="locations.branch",
                verbose_name="الفرع / مركز التدريب",
            ),
        ),
        migrations.AddField(
            model_name="traineeprofile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trainees",
                to="locations.branch",
                verbose_name="الفرع / مركز التدريب",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "مسؤول النظام (Super Admin)"),
                    ("governorate_admin", "مسؤول المحافظة"),
                    ("director", "مدير المبادرة"),
                    ("training_officer", "مسؤول التدريب"),
                    ("supervisor", "المشرف"),
                    ("lecturer", "المحاضر"),
                    ("trainee", "المتدرب"),
                    ("visitor", "الزائر"),
                ],
                default="visitor",
                max_length=20,
                verbose_name="الدور الوظيفي",
            ),
        ),
        migrations.AlterField(
            model_name="traineeprofile",
            name="governorate",
            field=models.CharField(max_length=50, verbose_name="المحافظة (السكن)"),
        ),
    ]
