# Generated by Django 5.1.15 on 2026-07-17 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("grades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturerevaluation",
            name="lecturer",
            field=models.ForeignKey(
                limit_choices_to={"role": "lecturer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_ratings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المحاضر",
            ),
        ),
        migrations.AddField(
            model_name="lecturerevaluation",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"role": "trainee"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_ratings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المتدرب المقيّم",
            ),
        ),
        migrations.AddField(
            model_name="traineeevaluation",
            name="evaluator",
            field=models.ForeignKey(
                limit_choices_to={"role": "lecturer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluations_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المقيّم",
            ),
        ),
        migrations.AddField(
            model_name="traineeevaluation",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_evaluations",
                to="courses.lecture",
                verbose_name="المحاضرة",
            ),
        ),
        migrations.AddField(
            model_name="traineeevaluation",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"role": "trainee"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainee_evaluations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المتدرب",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lecturerevaluation",
            unique_together={("lecture", "trainee")},
        ),
        migrations.AlterUniqueTogether(
            name="traineeevaluation",
            unique_together={("trainee", "lecture")},
        ),
    ]
