# Generated by Django 5.1.15 on 2026-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("absent", "غائب"),
                            ("late", "متأخر"),
                        ],
                        default="absent",
                        max_length=10,
                        verbose_name="حالة الحضور",
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت تسجيل الحضور"
                    ),
                ),
                (
                    "delay_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="دقائق التأخير"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("qr", "QR Code"),
                            ("barcode", "Barcode"),
                            ("manual", "يدوي"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="طريقة التحضير",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
            ],
            options={
                "verbose_name": "سجل الحضور",
                "verbose_name_plural": "سجلات الحضور",
            },
        ),
        migrations.CreateModel(
            name="LectureQRToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="الرمز المؤقت"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="تاريخ الانتهاء")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="خط العرض"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="خط الطول"),
                ),
                (
                    "radius_meters",
                    models.FloatField(
                        default=50.0, verbose_name="نطاق التحقق (بالمتر)"
                    ),
                ),
            ],
            options={
                "verbose_name": "رمز حضور QR",
                "verbose_name_plural": "رموز حضور QR",
            },
        ),
    ]
