# Generated by Django 5.1.15 on 2026-07-17 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0002_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"role": "trainee"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المتدرب",
            ),
        ),
        migrations.AddField(
            model_name="lectureqrtoken",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_tokens",
                to="courses.lecture",
                verbose_name="المحاضرة",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("trainee", "lecture")},
        ),
    ]
