# Generated by Django 5.1.15 on 2026-07-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "حاضر"),
                    ("absent", "غائب"),
                    ("late", "متأخر"),
                    ("excused", "مجاز"),
                ],
                default="absent",
                max_length=10,
                verbose_name="حالة الحضور",
            ),
        ),
    ]
