# Generated by Django 5.1.15 on 2026-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الواجب"),
                ),
                ("description", models.TextField(verbose_name="وصف الواجب")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignments/",
                        verbose_name="ملف مرفق",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(verbose_name="تاريخ الاستحقاق والتسليم"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "الواجب الدراسي",
                "verbose_name_plural": "الواجبات الدراسية",
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="submissions/", verbose_name="ملف الحل المرفوع"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التسليم"),
                ),
                (
                    "grade",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الدرجة"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات المصحح"
                    ),
                ),
            ],
            options={
                "verbose_name": "تسليم الواجب",
                "verbose_name_plural": "تسليمات الواجبات",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المشروع"),
                ),
                ("description", models.TextField(verbose_name="وصف المشروع")),
                (
                    "completion_percentage",
                    models.PositiveIntegerField(default=0, verbose_name="نسبة الإنجاز"),
                ),
                (
                    "github_repo",
                    models.URLField(
                        blank=True, null=True, verbose_name="مستودع GitHub"
                    ),
                ),
                (
                    "demo_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط التجربة (Demo)"
                    ),
                ),
                (
                    "grade",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الدرجة النهائية"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات وتوجيهات المدرب"
                    ),
                ),
            ],
            options={
                "verbose_name": "المشروع البرمجي",
                "verbose_name_plural": "المشاريع البرمجية",
            },
        ),
    ]
