# Generated by Django 5.1.15 on 2026-07-17 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "lecturer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المصحح",
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"role": "trainee"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المتدرب",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "lecturer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المدرب المقيّم",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="trainee",
            field=models.ForeignKey(
                limit_choices_to={"role": "trainee"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المتدرب",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentsubmission",
            unique_together={("assignment", "trainee")},
        ),
    ]
