# Generated by Django 5.1.4 on 2026-07-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="submissions/images/",
                verbose_name="صورة الحل المرفقة",
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="submission_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="نص الإجابة والملاحظات"
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="submissions/videos/",
                verbose_name="فيديو الحل المرفوع",
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="رابط فيديو الحل (YouTube/Drive)"
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="submissions/files/",
                verbose_name="ملف الحل المرفوع",
            ),
        ),
    ]
