# Generated by Django 5.1.15 on 2026-07-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="نص الإشعار")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "داخل النظام"),
                            ("email", "بريد إلكتروني"),
                            ("both", "كلاهما"),
                        ],
                        default="system",
                        max_length=10,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="تم القراءة؟"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
            ],
            options={
                "verbose_name": "الإشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InternalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="نص الرسالة")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="messages/",
                        verbose_name="ملف مرفق",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_messages",
                        to="courses.group",
                        verbose_name="المجموعة المستهدفة (جماعي)",
                    ),
                ),
            ],
            options={
                "verbose_name": "الرسالة الداخلية",
                "verbose_name_plural": "الرسائل الداخلية",
                "ordering": ["created_at"],
            },
        ),
    ]
