# Generated by Django 5.1.4 on 2026-07-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalmessage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="messages/images/",
                verbose_name="صورة مرفقة",
            ),
        ),
        migrations.AddField(
            model_name="internalmessage",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="مقروءة؟"),
        ),
        migrations.AlterField(
            model_name="internalmessage",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="نص الرسالة"),
        ),
        migrations.AlterField(
            model_name="internalmessage",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="messages/files/",
                verbose_name="ملف مرفق",
            ),
        ),
    ]
