# Generated by Django 5.1.4 on 2026-07-30 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_dailyreport"),
        (
            "notifications",
            "0003_internalmessage_image_internalmessage_is_read_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="internalmessage",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_messages",
                to="courses.course",
                verbose_name="المادة الدراسية المستهدفة",
            ),
        ),
    ]
